# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RamdomLaunch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RamdomLaunch
pod 'lottie-ios'
  target 'RamdomLaunchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RamdomLaunchUITests' do
    # Pods for testing
  end

end
